ALTER TABLE `fiesta_world`.`groups`
CHANGE COLUMN
	`Master`
	`Member5` int(10) UNSIGNED NULL DEFAULT NULL,
CHANGE COLUMN 
	`Member2`
	`Member2` int(10) UNSIGNED NULL DEFAULT NULL,
CHANGE COLUMN
	`Member3`
	`Member3` int(10) UNSIGNED NULL DEFAULT NULL,
CHANGE COLUMN
	`Member4`
	`Member4` int(10) UNSIGNED NULL DEFAULT NULL;
