//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("LoginModel", "FK_access_level", "access_levels", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DragonFiesta.Database.EF_Models.access_levels), "accounts", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DragonFiesta.Database.EF_Models.account), true)]

#endregion

namespace DragonFiesta.Database.EF_Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class AccountEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new AccountEntities object using the connection string found in the 'AccountEntities' section of the application configuration file.
        /// </summary>
        public AccountEntities() : base("name=AccountEntities", "AccountEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AccountEntities object.
        /// </summary>
        public AccountEntities(string connectionString) : base(connectionString, "AccountEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new AccountEntities object.
        /// </summary>
        public AccountEntities(EntityConnection connection) : base(connection, "AccountEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<access_levels> access_levels
        {
            get
            {
                if ((_access_levels == null))
                {
                    _access_levels = base.CreateObjectSet<access_levels>("access_levels");
                }
                return _access_levels;
            }
        }
        private ObjectSet<access_levels> _access_levels;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<account> accounts
        {
            get
            {
                if ((_accounts == null))
                {
                    _accounts = base.CreateObjectSet<account>("accounts");
                }
                return _accounts;
            }
        }
        private ObjectSet<account> _accounts;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<hash> hashes
        {
            get
            {
                if ((_hashes == null))
                {
                    _hashes = base.CreateObjectSet<hash>("hashes");
                }
                return _hashes;
            }
        }
        private ObjectSet<hash> _hashes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<version> versions
        {
            get
            {
                if ((_versions == null))
                {
                    _versions = base.CreateObjectSet<version>("versions");
                }
                return _versions;
            }
        }
        private ObjectSet<version> _versions;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<v_Auth> v_Auth
        {
            get
            {
                if ((_v_Auth == null))
                {
                    _v_Auth = base.CreateObjectSet<v_Auth>("v_Auth");
                }
                return _v_Auth;
            }
        }
        private ObjectSet<v_Auth> _v_Auth;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the access_levels EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaccess_levels(access_levels access_levels)
        {
            base.AddObject("access_levels", access_levels);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the accounts EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToaccounts(account account)
        {
            base.AddObject("accounts", account);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the hashes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTohashes(hash hash)
        {
            base.AddObject("hashes", hash);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the versions EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToversions(version version)
        {
            base.AddObject("versions", version);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the v_Auth EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTov_Auth(v_Auth v_Auth)
        {
            base.AddObject("v_Auth", v_Auth);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LoginModel", Name="access_levels")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class access_levels : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new access_levels object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="can_login">Initial value of the can_login property.</param>
        public static access_levels Createaccess_levels(global::System.Int64 id, global::System.String name, global::System.Boolean can_login)
        {
            access_levels access_levels = new access_levels();
            access_levels.id = id;
            access_levels.name = name;
            access_levels.can_login = can_login;
            return access_levels;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean can_login
        {
            get
            {
                return _can_login;
            }
            set
            {
                Oncan_loginChanging(value);
                ReportPropertyChanging("can_login");
                _can_login = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("can_login");
                Oncan_loginChanged();
            }
        }
        private global::System.Boolean _can_login;
        partial void Oncan_loginChanging(global::System.Boolean value);
        partial void Oncan_loginChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LoginModel", "FK_access_level", "accounts")]
        public EntityCollection<account> accounts
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<account>("LoginModel.FK_access_level", "accounts");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<account>("LoginModel.FK_access_level", "accounts", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LoginModel", Name="account")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class account : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new account object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="password">Initial value of the password property.</param>
        /// <param name="access_level">Initial value of the access_level property.</param>
        public static account Createaccount(global::System.Int64 id, global::System.String name, global::System.String password, global::System.Int64 access_level)
        {
            account account = new account();
            account.id = id;
            account.name = name;
            account.password = password;
            account.access_level = access_level;
            return account;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                OnpasswordChanging(value);
                ReportPropertyChanging("password");
                _password = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("password");
                OnpasswordChanged();
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 access_level
        {
            get
            {
                return _access_level;
            }
            set
            {
                Onaccess_levelChanging(value);
                ReportPropertyChanging("access_level");
                _access_level = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("access_level");
                Onaccess_levelChanged();
            }
        }
        private global::System.Int64 _access_level;
        partial void Onaccess_levelChanging(global::System.Int64 value);
        partial void Onaccess_levelChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("LoginModel", "FK_access_level", "access_levels")]
        public access_levels access_levels
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<access_levels>("LoginModel.FK_access_level", "access_levels").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<access_levels>("LoginModel.FK_access_level", "access_levels").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<access_levels> access_levelsReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<access_levels>("LoginModel.FK_access_level", "access_levels");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<access_levels>("LoginModel.FK_access_level", "access_levels", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LoginModel", Name="hash")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class hash : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new hash object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="hash_string">Initial value of the hash_string property.</param>
        /// <param name="allow_login">Initial value of the allow_login property.</param>
        public static hash Createhash(global::System.Int64 id, global::System.String hash_string, global::System.Boolean allow_login)
        {
            hash hash = new hash();
            hash.id = id;
            hash.hash_string = hash_string;
            hash.allow_login = allow_login;
            return hash;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String hash_string
        {
            get
            {
                return _hash_string;
            }
            set
            {
                Onhash_stringChanging(value);
                ReportPropertyChanging("hash_string");
                _hash_string = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("hash_string");
                Onhash_stringChanged();
            }
        }
        private global::System.String _hash_string;
        partial void Onhash_stringChanging(global::System.String value);
        partial void Onhash_stringChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean allow_login
        {
            get
            {
                return _allow_login;
            }
            set
            {
                Onallow_loginChanging(value);
                ReportPropertyChanging("allow_login");
                _allow_login = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("allow_login");
                Onallow_loginChanged();
            }
        }
        private global::System.Boolean _allow_login;
        partial void Onallow_loginChanging(global::System.Boolean value);
        partial void Onallow_loginChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LoginModel", Name="v_Auth")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class v_Auth : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new v_Auth object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="password">Initial value of the password property.</param>
        /// <param name="can_login">Initial value of the can_login property.</param>
        public static v_Auth Createv_Auth(global::System.Int64 id, global::System.String name, global::System.String password, global::System.Boolean can_login)
        {
            v_Auth v_Auth = new v_Auth();
            v_Auth.id = id;
            v_Auth.name = name;
            v_Auth.password = password;
            v_Auth.can_login = can_login;
            return v_Auth;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                if (_name != value)
                {
                    OnnameChanging(value);
                    ReportPropertyChanging("name");
                    _name = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("name");
                    OnnameChanged();
                }
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String password
        {
            get
            {
                return _password;
            }
            set
            {
                if (_password != value)
                {
                    OnpasswordChanging(value);
                    ReportPropertyChanging("password");
                    _password = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("password");
                    OnpasswordChanged();
                }
            }
        }
        private global::System.String _password;
        partial void OnpasswordChanging(global::System.String value);
        partial void OnpasswordChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean can_login
        {
            get
            {
                return _can_login;
            }
            set
            {
                if (_can_login != value)
                {
                    Oncan_loginChanging(value);
                    ReportPropertyChanging("can_login");
                    _can_login = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("can_login");
                    Oncan_loginChanged();
                }
            }
        }
        private global::System.Boolean _can_login;
        partial void Oncan_loginChanging(global::System.Boolean value);
        partial void Oncan_loginChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="LoginModel", Name="version")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class version : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new version object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="year">Initial value of the year property.</param>
        /// <param name="version_number">Initial value of the version_number property.</param>
        /// <param name="allowed">Initial value of the allowed property.</param>
        public static version Createversion(global::System.Int64 id, global::System.Int32 year, global::System.Int32 version_number, global::System.Boolean allowed)
        {
            version version = new version();
            version.id = id;
            version.year = year;
            version.version_number = version_number;
            version.allowed = allowed;
            return version;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 year
        {
            get
            {
                return _year;
            }
            set
            {
                OnyearChanging(value);
                ReportPropertyChanging("year");
                _year = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("year");
                OnyearChanged();
            }
        }
        private global::System.Int32 _year;
        partial void OnyearChanging(global::System.Int32 value);
        partial void OnyearChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 version_number
        {
            get
            {
                return _version_number;
            }
            set
            {
                Onversion_numberChanging(value);
                ReportPropertyChanging("version_number");
                _version_number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version_number");
                Onversion_numberChanged();
            }
        }
        private global::System.Int32 _version_number;
        partial void Onversion_numberChanging(global::System.Int32 value);
        partial void Onversion_numberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Boolean allowed
        {
            get
            {
                return _allowed;
            }
            set
            {
                OnallowedChanging(value);
                ReportPropertyChanging("allowed");
                _allowed = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("allowed");
                OnallowedChanged();
            }
        }
        private global::System.Boolean _allowed;
        partial void OnallowedChanging(global::System.Boolean value);
        partial void OnallowedChanged();

        #endregion

    
    }

    #endregion

    
}
